version: '3'
services:
  build_tasmanian:
    image: dalg24/tasmanian_stack
    environment:
      - NPROC=4
      - BUILD_TYPE=$BUILD_TYPE
    volumes:
        - jenkins_data:${WORKSPACE}/../..
    network_mode: host
    working_dir: $WORKSPACE
    command: $WORKSPACE/docker/jenkins/build.sh
volumes:
  jenkins_data:
    external:
      name: $JENKINS_DATA_VOLUME

